- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    user: "{{ lookup('env', 'USER') }}"
    email: "hugowalkersmith@gmail.com"
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/kitty.yml
    - import_tasks: tasks/dotfiles.yml

