- name: install apps
  community.general.homebrew_cask:
    name: "{{ applications }}"
    state: present
    update_homebrew: true
  vars:
    applications:
      - firefox
      - ghostty
      - google-chrome
      - nordvpn
      - obsidian
      - podman-desktop
      - rectangle
      - spotify
      - syncthing
      - vlc
  tags:
    - apps
