- name: install apps
  become: true
  community.general.homebrew_cask:
    name: "{{ applications }}"
    state: present
    update_homebrew: true
  vars:
    applications:
      - firefox
      - ghostty
      - obsidian
      - rectangle
      - spotify
      - syncthing
  tags:
    - apps
