- name: download awscli
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscli-bundle.zip
  tags:
    - aws

- name: unarchive awscli
  become: true
  unarchive:
    src: /tmp/awscli-bundle.zip
    dest: /tmp
    creates: /tmp/awscli-bundle
  tags:
    - aws

- name: check whether awscli is installed
  shell:
    cmd: which aws
  register: aws_already_installed 
  tags:
    - aws

- name: install awscli if not installed
  become: true
  shell:
    cmd: ./install
    chdir: /tmp/aws
  when: aws_already_installed.rc != 0
  tags:
    - aws

- name: update awscli if already installed
  become: true
  shell:
    cmd: "./install --bin-dir {{ aws_already_installed.stdout }} --install-dir /usr/local/aws-cli --update"
    chdir: /tmp/aws
  when: aws_already_installed.rc == 0
  tags:
    - aws

- name: ensure .aws directory exists
  file:
    dest: "{{ aws_dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - aws

- name: install aws credentials file
  copy:
    src: "{{ aws_source_key }}"
    dest: "{{ aws_dest_key }}"
    mode: 0600
  tags:
    - aws

- name: configure aws
  shell:
    cmd: aws configure set {{ item.key }} {{ item.value }}
  with_dict:
    region: "ap-southeast-2"
    format: "json"
  tags:
    - aws
