- name: remove unofficial docker packages
  become: true
  dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
  tags:
    - docker

- name: add docker repository
  become: true
  shell:
    cmd: "dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"
  tags:
    - docker

- name: install docker packages (also create docker group)
  become: true
  dnf:
    update_cache: true
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tags:
    - docker

- name: add user to docker group
  become: true
  shell:
    cmd: "usermod -aG docker {{ user }}"
  tags:
    - docker

- name: configure docker daemon to start on boot
  become: true
  shell:
    cmd: "systemctl enable --now docker"
  tags:
    - docker
