- name: install stow
  become: true
  dnf:
    update_cache: true
    name: stow
    state: latest
  tags:
    - dotfiles

- name: clone dotfiles
  git:
    repo: 'git@github.com:walkerh1/dotfiles.git'
    dest: "{{ home }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles

- name: stow dotfiles
  command: ./run_stow.sh
  args:
    chdir: "{{ home }}/dotfiles"
  tags:
    - dotfiles
