- name: install stow
  community.general.homebrew:
    name: stow
    state: latest
    update_homebrew: true
  tags:
    - dotfiles

- name: clone dotfiles
  git:
    repo: 'git@github.com:walkerh1/dotfiles.git'
    dest: "{{ home }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles

- name: stow dotfiles
  command: ./run_stow.sh
  args:
    chdir: "{{ home }}/dotfiles"
  tags:
    - dotfiles
