- name: remove JetBrainsMono fonts directory
  file:
    path: "{{ home }}/.local/share/fonts/JetBrainsMono"
    state: absent
  tags:
    - fonts

- name: create JetBrainsMono fonts directory
  file:
    path: "{{ home }}/.local/share/fonts/JetBrainsMono"
    state: directory
  tags:
    - fonts

- name: download and unarchive JetBrainsMono fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.tar.xz
    dest: "{{ home }}/.local/share/fonts/JetBrainsMono"
    remote_src: yes
  tags:
    - fonts
