- name: user.name for git config
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ username }}"
  tags:
    - git

- name: user.email for git config
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
  tags:
    - git
