- name: download kitty
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    dest: /tmp/kitty_installer.sh
  tags:
    - kitty

- name: install kitty
  command: sh /tmp/kitty_installer.sh
  register: kitty_result
  failed_when: "'FAILED' in kitty_result.stderr"
  tags:
    - kitty

- name: ensure .local/bin directory exists
  file:
    path: "{{ home }}/.local/bin"
    state: directory
  tags:
    - kitty

- name: make kitty binaries visible to system
  command: "ln -sf {{ home }}/.local/kitty.app/bin/kitty {{ home }}/.local/kitty.app/bin/kitten {{ home }}/.local/bin"
  tags:
    - kitty
