- name: remove old version of neovim
  become: true
  file:
    path: "{{ home }}/neovim"
    state: absent
  tags:
    - neovim

- name: clone neovim
  git:
    repo: "git@github.com:neovim/neovim.git"
    dest: "{{ home }}/neovim"
    depth: 1
    version: stable
  tags:
    - neovim

- name: install neovim build deps
  become: true
  dnf:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ninja-build
      - gettext
      - cmake
      - gcc
      - make
      - unzip
      - curl
      - glibc-gconv-extra
  tags:
    - neovim

- name: build neovim
  become: true
  command: make install
  args:
    chdir: "{{ home }}/neovim"
  tags:
    - neovim

- name: install neovim peer deps
  become: true
  dnf:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ripgrep
  tags:
    - neovim
