- name: install obsidian
  community.general.flatpak:
    name: md.obsidian.Obsidian
    state: latest
  tags:
    - obsidian

- name: install syncthing
  become: true
  dnf:
    update_cache: yes
    name: syncthing
    state: latest
  tags:
    - obsidian

- name: configure syncthing to start on login and after updates
  shell: |
    systemctl --user enable --now syncthing.service
    systemctl --user daemon-reload
    systemctl --user restart syncthing.service
  tags:
    - obsidian
