- name: install tools
  become: true
  dnf:
    update_cache: yes
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - bat
      - dnf-plugins-core
      - fzf
      - golang
      - ripgrep
      - tmux
      - tree
  tags:
    - tools
