- name: install tools
  community.general.homebrew:
    name: "{{ packages }}"
    state: latest
    update_homebrew: true
  vars:
    packages:
      - bat
      - fd
      - ffmpeg
      - fish
      - fnm
      - fzf
      - go
      - hey
      - jq
      - lua-language-server
      - neovim
      - ripgrep
      - tmux
      - tree
      - tree-sitter-cli
      - typescript
      - typescript-language-server
      - vscode-langservers-extracted
  tags:
    - tools
